### ISSUE TITLE
Audit coverage of python API unit-tests

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#139]
## Definition of Done
Identified any gaps in unit-tests of the API, if any then create another issue listing those gaps. Aim for 80% coverage for codecov

**Comment by Bento007** [comment]
currently we are at 70.32% since adding coverage. 

- api/python/cell_census has 93.80% coverage
- tools/cell_census_builder/ has 65.63% coverage
  - In tools/cell_census_builder/__main__.py the following functions are not covered `create_args_parser`, `build_step1_get_source_assets`, `prepare_file_system`, `main`
  - In tools/cell_census_builder/anndata.py there are a lot of if condition not tested
  - tools/cell_census_builder/consolidate.py is not covered.
  - tools/cell_census_builder/manifest.py is not covered
  - in tools/cell_census_builder/mp.py `cpu_count` and `create_process_pool_executor` not covered
  - in tools/cell_census_builder/source_assets.py `stage_source_assets` and `_copy_file` not covered
  - tools/cell_census_builder/validate.py is not covered

**Comment by Bento007** [comment]
Add issues for all gaps in coverage that should be addressed
