### ISSUE TITLE
Add tests for different code paths in tools/cell_census_builder/tissue_mapper.py

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cell-census#197]
## Motivation

The goal is to at least have coverage for all of the positive test paths.

## Definition of Done

Add unit tests that cover the logic flows in `TissueMapper.get_high_level_tissue`

**Comment by ebezzi** [comment]
I noticed that this code is extracted from the data portal, which has its own test. We have a few options:
1. Leave it as is
1. Copy the test as well
1. Package it into a new library
1. Package it into cellxgene-schema and publish a new version

3. is obviously the best solution but will involve a bit of coordination since we'll have to create a new repo and pypi library. I also know there is some work scheduled for an
"ontology service", which would naturally include this method, but I don't know the ETA.

4. is a decent solution but adds a dependency that we might not need (although technically the census depends on the cellxgene schema to work, so might not be so bad...)
Thoughts?

**Comment by ebezzi** [comment]
I'm proposing that we reject this ticket and replace it with an "use the Ontology Service when available to replace tissue_mapper.py". I don't think we should copy the test over from the data portal as that will increase data duplication. I would add a comment at the top of the file with the new ticket number and with a note to not modify the file (unless the same change is also applied to the data portal).

@Bento007 any thoughts on the above approach?
